### ISSUE TITLE
Upgrade MySQL client version

### ISSUE THREAD

**Issue by fstagni** [DIRACGrid/DIRACOS#97] opened 2019-09-26 09:46 UTC
...to work with MySQL 8

**Comment by fstagni** [comment] 2019-09-26 09:46
See https://github.com/DIRACGrid/DIRAC/pull/4286

**Comment by chrisburr** [comment] 2019-09-26 10:16
[5.7.23 or later is required](https://dev.mysql.com/doc/relnotes/mysql/5.7/en/news-5-7-23.html#mysqld-5-7-23-security) for MySQL 8.0 so the `caching_sha2_password` module is included.

**Comment by chaen** [comment] 2019-09-26 12:47
Closing as duplicate of https://github.com/DIRACGrid/DIRACOS/issues/78

**Closed by chaen** 2019-09-26 12:47 UTC
